"""Substrate enrichment orchestrator.

Reads the live substrate (anon, read-only), runs the two correctness/anti-hallucination
stages, and emits a reviewable migration + JSON report. Writes NOTHING to the database
directly (same generated-migration pattern as the rest of scripts/substrate/).

  1. Source validation  -> validate_sources.py (PMID resolves at NCBI, title matches)
  2. Ontology grounding -> ground_entities.py  (RxNorm / MONDO identifiers)

Outputs:
  supabase/migrations/048_substrate_grounding.sql   (apply in Supabase Studio, after 047)
  scripts/substrate/audit-output/enrichment-report.json

Run from repo root:  python3 scripts/substrate/run_enrichment.py
"""
import json
from datetime import datetime, timezone

import sb
import validate_sources
import ground_entities
from config import MIGRATIONS_DIR, SUBSTRATE_DIR

SEED = MIGRATIONS_DIR / "048_substrate_grounding.sql"
REPORT = SUBSTRATE_DIR / "audit-output" / "enrichment-report.json"


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def build_sql(src_results, ent_results):
    L = []
    L.append("-- ============================================================")
    L.append("-- 048_substrate_grounding.sql")
    L.append("-- Source validation + ontology-grounded entity resolution")
    L.append("-- ============================================================")
    L.append("-- Generated by scripts/substrate/run_enrichment.py. Apply AFTER 047,")
    L.append("-- in Supabase Studio. Additive and idempotent (IF NOT EXISTS / keyed UPDATEs).")
    L.append("--")
    L.append("-- Adds, per document, whether its PMID resolves at NCBI and the stored title")
    L.append("-- matches the canonical record (anti-hallucination / citation validation), and")
    L.append("-- per entity, a canonical registry identifier (RxNorm for interventions, MONDO")
    L.append("-- for conditions).")
    L.append(f"-- Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    L.append("")
    L.append("BEGIN;")
    L.append("")
    L.append("alter table documents add column if not exists source_status text;")
    L.append("alter table documents add column if not exists canonical_title text;")
    L.append("alter table documents add column if not exists title_similarity numeric;")
    L.append("alter table documents add column if not exists source_checked_at timestamptz;")
    L.append("alter table entities  add column if not exists ontology_source text;")
    L.append("alter table entities  add column if not exists canonical_label text;")
    L.append("")
    L.append(f"-- documents: {len(src_results)} source-validation result(s)")
    for r in src_results:
        L.append(
            "update documents set "
            f"source_status = {q(r['status'])}, "
            f"canonical_title = {q(r['canonical_title'])}, "
            f"title_similarity = {q(r['title_similarity'])}, "
            f"source_checked_at = {q(r['checked_at'])}::timestamptz "
            f"where id = {q(r['id'])};")
    L.append("")
    grounded = [r for r in ent_results if r["ontology_id"]]
    L.append(f"-- entities: {len(grounded)} grounded of {len(ent_results)} (unresolved left NULL)")
    for r in grounded:
        L.append(
            "update entities set "
            f"ontology_id = {q(r['ontology_id'])}, "
            f"ontology_source = {q(r['ontology_source'])}, "
            f"canonical_label = {q(r['canonical_label'])} "
            f"where id = {q(r['id'])};")
    L.append("")
    L.append("COMMIT;")
    L.append("")
    L.append("-- Verify after apply:")
    L.append("--   select source_status, count(*) from documents group by source_status;")
    L.append("--   select type, count(ontology_id) grounded, count(*) total from entities group by type;")
    L.append("")
    return "\n".join(L)


def main():
    print("== Substrate enrichment ==")
    print("\n[1/2] Source validation (NCBI citation check) ...")
    docs = sb.get("documents?select=id,external_id,title")
    src = validate_sources.validate(docs)

    print("\n[2/2] Ontology-grounded entity resolution ...")
    ents = sb.get("entities?select=id,type,label&order=type")
    grounded = ground_entities.ground(ents)

    SEED.write_text(build_sql(src, grounded))
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(json.dumps({
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source_validation": src,
        "entity_grounding": grounded,
    }, indent=2) + "\n")
    print(f"\nwrote {SEED}")
    print(f"wrote {REPORT}")
    print("\nNext: apply 048 in Supabase Studio (after 047).")


if __name__ == "__main__":
    main()
