"""Emit supabase/migrations/047_substrate_seed_pmdd.sql from the local working
store, plus a JSON run log. Mirrors the pattern of extract-key-findings.py: the
pipeline never writes to the production database; it generates a reviewable
migration that gets applied in Supabase Studio.

The seed is idempotent: every INSERT uses ON CONFLICT (id) DO NOTHING, and the
column shapes map 1:1 onto migration 046.
"""
import json
from datetime import datetime, timezone

import db
from config import SEED_MIGRATION, RUN_LOG


def q(v):
    """Render a Python value as a Postgres literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def _insert(table, cols, rows, conflict="id"):
    if not rows:
        return [f"-- {table}: (none)\n"]
    out = [f"-- {table}: {len(rows)} row(s)"]
    collist = ", ".join(cols)
    for r in rows:
        vals = ", ".join(q(r[c]) for c in cols)
        out.append(f"INSERT INTO {table} ({collist}) VALUES ({vals}) "
                   f"ON CONFLICT ({conflict}) DO NOTHING;")
    out.append("")
    return out


def build_sql(conn):
    L = []
    L.append("-- ============================================================")
    L.append("-- 047_substrate_seed_pmdd.sql")
    L.append("-- PMDD/PMS substrate seed — generated by scripts/substrate/run.py")
    L.append("-- ============================================================")
    L.append("--")
    L.append("-- Inserts the substrate the pipeline built (documents → source_spans →")
    L.append("-- claims → contradictions, plus entities) into the tables created by")
    L.append("-- migration 046. Apply AFTER 046, in Supabase Studio (SQL Editor).")
    L.append("--")
    L.append("-- Idempotent: every INSERT is ON CONFLICT (id) DO NOTHING. Safe to re-run.")
    L.append(f"-- Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    L.append("")
    L.append("BEGIN;")
    L.append("")

    ents = conn.execute("SELECT id, type, label, norm_key, ontology_id FROM entities").fetchall()
    L += _insert("entities", ["id", "type", "label", "norm_key", "ontology_id"], ents)

    docs = conn.execute(
        "SELECT id, content_sha256, source, external_id, url, title, raw_text, retrieved_at, meta_json"
        " FROM documents").fetchall()
    dl = ["-- documents: %d row(s)" % len(docs)]
    for d in docs:
        meta = f"{q(d['meta_json'])}::jsonb" if d["meta_json"] else "NULL"
        dl.append(
            "INSERT INTO documents (id, content_sha256, source, external_id, url, title, raw_text,"
            " retrieved_at, meta) VALUES ("
            f"{q(d['id'])}, {q(d['content_sha256'])}, {q(d['source'])}, {q(d['external_id'])}, "
            f"{q(d['url'])}, {q(d['title'])}, {q(d['raw_text'])}, {q(d['retrieved_at'])}, {meta}) "
            "ON CONFLICT (id) DO NOTHING;")
    dl.append("")
    L += dl

    spans = conn.execute(
        "SELECT id, document_id, start_char, end_char, text, sha256, ordinal, extracted"
        " FROM source_spans").fetchall()
    sl = ["-- source_spans: %d row(s)" % len(spans)]
    for s in spans:
        sl.append(
            "INSERT INTO source_spans (id, document_id, start_char, end_char, text, sha256, ordinal,"
            " extracted) VALUES ("
            f"{q(s['id'])}, {q(s['document_id'])}, {q(s['start_char'])}, {q(s['end_char'])}, "
            f"{q(s['text'])}, {q(s['sha256'])}, {q(s['ordinal'])}, {q(bool(s['extracted']))}) "
            "ON CONFLICT (id) DO NOTHING;")
    sl.append("")
    L += sl

    claims = conn.execute(
        "SELECT id, span_id, document_id, text, exact_quote, quote_start_char, quote_end_char,"
        " intervention_id, condition_id, outcome, aspect, direction, provenance_verified,"
        " entailment_label, entailment_score, model_name, prompt_hash, created_at FROM claims").fetchall()
    cl = ["-- claims: %d row(s)" % len(claims)]
    for c in claims:
        cl.append(
            "INSERT INTO claims (id, span_id, document_id, text, exact_quote, quote_start_char,"
            " quote_end_char, intervention_id, condition_id, outcome, aspect, direction,"
            " provenance_verified, entailment_label, entailment_score, model_name, prompt_hash,"
            " created_at) VALUES ("
            f"{q(c['id'])}, {q(c['span_id'])}, {q(c['document_id'])}, {q(c['text'])}, "
            f"{q(c['exact_quote'])}, {q(c['quote_start_char'])}, {q(c['quote_end_char'])}, "
            f"{q(c['intervention_id'])}, {q(c['condition_id'])}, {q(c['outcome'])}, {q(c['aspect'])}, "
            f"{q(c['direction'])}, {q(bool(c['provenance_verified']))}, {q(c['entailment_label'])}, "
            f"{q(c['entailment_score'])}, {q(c['model_name'])}, {q(c['prompt_hash'])}, {q(c['created_at'])}) "
            "ON CONFLICT (id) DO NOTHING;")
    cl.append("")
    L += cl

    contras = conn.execute(
        "SELECT id, claim_a_id, claim_b_id, intervention_id, condition_id, nli_label, nli_score,"
        " rationale, model_name, created_at FROM contradictions").fetchall()
    L += _insert("contradictions",
                 ["id", "claim_a_id", "claim_b_id", "intervention_id", "condition_id",
                  "nli_label", "nli_score", "rationale", "model_name", "created_at"],
                 contras)

    L.append("COMMIT;")
    L.append("")
    L.append("-- Verify after apply:")
    L.append("--   select 'documents' t, count(*) from documents")
    L.append("--   union all select 'claims', count(*) from claims")
    L.append("--   union all select 'contradictions', count(*) from contradictions;")
    L.append("")
    return "\n".join(L)


def run(usage=None):
    conn = db.connect()
    SEED_MIGRATION.write_text(build_sql(conn))

    counts = {t: conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
              for t in ["documents", "source_spans", "claims", "contradictions", "entities"]}
    counts["claims_provenance_verified"] = conn.execute(
        "SELECT COUNT(*) FROM claims WHERE provenance_verified=1").fetchone()[0]
    counts["claims_entailment_labeled"] = conn.execute(
        "SELECT COUNT(*) FROM claims WHERE entailment_label IS NOT NULL").fetchone()[0]
    log = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "counts": counts,
        "usage": usage or {},
        "seed_migration": str(SEED_MIGRATION.relative_to(SEED_MIGRATION.parents[2])),
    }
    RUN_LOG.write_text(json.dumps(log, indent=2) + "\n")
    print(f"  wrote {SEED_MIGRATION}")
    print(f"  wrote {RUN_LOG}")
    return counts


if __name__ == "__main__":
    run()
