-- 043_backfill_guideline_curation.sql
-- Auto-generated by scripts/curate-guidelines.py
-- on 2026-06-06T00:56:42Z. Do not hand-edit; re-run --apply.
--
-- Curates guideline_id + guideline_strength + guideline_certainty
-- on `sources` rows previously classified study_type='guideline'.
-- Unlocks the L3 path in scripts/check-matrix-coverage.py Phase 6
-- for every signal that has at least one source row covered here.
--
-- Coverage: 3 rows curated in this batch.
--
-- guideline body distribution (prefix-of-guideline_id):
--   ESHRE                 1
--   ISSWSH                1
--   NAMS                  1
--
-- guideline_strength distribution:
--   recommended           2
--   weak                  1
--
-- guideline_certainty distribution:
--   moderate              2
--   low                   1

BEGIN;

UPDATE sources SET guideline_id        = 'ESHRE-2022-Endometriosis-ContinuousCOC-Dysmenorrhoea', guideline_strength  = 'weak', guideline_certainty = 'low' WHERE id = '15956dc9-2a06-4d1b-9255-f9bf8e2f394f';
UPDATE sources SET guideline_id        = 'ISSWSH-2021-HSDD-Testosterone', guideline_strength  = 'recommended', guideline_certainty = 'moderate' WHERE id = '9828bb10-6ecc-422c-9f79-d3e3472daea6';
UPDATE sources SET guideline_id        = 'NAMS-2020-GSM-VaginalEstrogen', guideline_strength  = 'recommended', guideline_certainty = 'moderate' WHERE id = 'cd3fec23-b272-47a1-9d25-905736f0729c';

COMMIT;
