-- ============================================================
-- 048_substrate_grounding.sql
-- Source validation + ontology-grounded entity resolution
-- ============================================================
-- Generated by scripts/substrate/run_enrichment.py. Apply AFTER 047,
-- in Supabase Studio. Additive and idempotent (IF NOT EXISTS / keyed UPDATEs).
--
-- Adds, per document, whether its PMID resolves at NCBI and the stored title
-- matches the canonical record (anti-hallucination / citation validation), and
-- per entity, a canonical registry identifier (RxNorm for interventions, MONDO
-- for conditions).
-- Generated: 2026-06-11T20:58:58+00:00

BEGIN;

alter table documents add column if not exists source_status text;
alter table documents add column if not exists canonical_title text;
alter table documents add column if not exists title_similarity numeric;
alter table documents add column if not exists source_checked_at timestamptz;
alter table entities  add column if not exists ontology_source text;
alter table entities  add column if not exists canonical_label text;

-- documents: 4 source-validation result(s)
update documents set source_status = 'resolved_match', canonical_title = 'The impact of essential fatty acid, B vitamins, vitamin C, magnesium and zinc supplementation on stress levels in women: a systematic review.', title_similarity = 1.0, source_checked_at = '2026-06-11T20:56:36+00:00'::timestamptz where id = '89232a08-3733-41d5-bb81-7d80dd14d4d6';
update documents set source_status = 'resolved_match', canonical_title = 'Vitex agnus-castus extracts for female reproductive disorders: a systematic review of clinical trials.', title_similarity = 1.0, source_checked_at = '2026-06-11T20:56:37+00:00'::timestamptz where id = '6e79669d-8252-4742-93f2-4496a8ae52c8';
update documents set source_status = 'resolved_match', canonical_title = 'Premenstrual syndrome.', title_similarity = 1.0, source_checked_at = '2026-06-11T20:56:38+00:00'::timestamptz where id = 'a4c6bdad-8758-4c37-9e9d-35ebf559653f';
update documents set source_status = 'resolved_match', canonical_title = 'Efficacy of vitamin B-6 in the treatment of premenstrual syndrome: systematic review.', title_similarity = 1.0, source_checked_at = '2026-06-11T20:56:38+00:00'::timestamptz where id = 'e02a6ae1-d777-49c6-afa2-305aab5b7f63';

-- entities: 6 grounded of 11 (unresolved left NULL)
update entities set ontology_id = 'MONDO:1010182', ontology_source = 'MONDO', canonical_label = 'premenstrual dysphoric disorder' where id = '37006837-7164-403c-aaa9-c22dccd914ec';
update entities set ontology_id = 'MONDO:0004169', ontology_source = 'MONDO', canonical_label = 'premenstrual tension' where id = '1a8845c9-b8e8-4d23-95d6-1baef05ae6ad';
update entities set ontology_id = 'RxNorm:4493', ontology_source = 'RxNorm', canonical_label = 'fluoxetine' where id = '4d47ac5e-e989-4168-b10c-0b942105c56a';
update entities set ontology_id = 'RxNorm:62356', ontology_source = 'RxNorm', canonical_label = 'folate' where id = '757c3a0a-28c4-4dca-908f-87d2a845e2b6';
update entities set ontology_id = 'RxNorm:11248', ontology_source = 'RxNorm', canonical_label = 'vitamin B12' where id = '3b6d2ff7-767b-4ef7-83d7-c39c04e60a2d';
update entities set ontology_id = 'RxNorm:42954', ontology_source = 'RxNorm', canonical_label = 'vitamin B6' where id = 'c0c40a17-959d-4c16-a499-20e8a08f36b3';

COMMIT;

-- Verify after apply:
--   select source_status, count(*) from documents group by source_status;
--   select type, count(ontology_id) grounded, count(*) total from entities group by type;
