-- 050_path_a_canonical_ids.sql
--
-- Path A (knowledge-graph substrate): add canonical-identifier columns to the
-- core entity tables so every drug and condition carries a stable, registry-backed
-- ID instead of a display-name string. This is the prerequisite for the graph: a
-- name-only key cannot be joined reliably to Open Targets, ChEMBL, MATRIX, or any
-- ontology.
--
-- This migration ONLY widens the schema. No data is altered here. The values are
-- backfilled by migration 051 (generated by scripts/resolve-canonical-ids.py),
-- which resolves names against free registries (ChEMBL, RxNorm) and the curated
-- condition map in lib/conditions-ontology.json, and flags anything that does not
-- resolve for human review rather than guessing.

-- ── compounds ───────────────────────────────────────────────────────────────
alter table compounds add column if not exists chembl_id   text;  -- e.g. CHEMBL25
alter table compounds add column if not exists rxcui       text;  -- RxNorm RXCUI
alter table compounds add column if not exists drugbank_id text;  -- reserved; DrugBank is Planned
alter table compounds add column if not exists atc_code    text;  -- WHO ATC, when ChEMBL exposes it

-- resolution_status drives the human-review worklist:
--   'resolved'   = at least one canonical id with name agreement
--   'ambiguous'  = a registry returned a candidate but the name did not cleanly match
--   'unresolved' = no registry match
alter table compounds add column if not exists resolution_status text;

-- ── conditions ──────────────────────────────────────────────────────────────
alter table conditions add column if not exists mondo_id text;  -- e.g. MONDO:0005133
alter table conditions add column if not exists efo_id   text;  -- e.g. EFO_0001065 (nullable; not all six have one)

-- ── indexes (canonical ids are join keys) ───────────────────────────────────
create index if not exists compounds_chembl_id_idx  on compounds (chembl_id);
create index if not exists compounds_rxcui_idx       on compounds (rxcui);
create index if not exists conditions_mondo_id_idx   on conditions (mondo_id);
