-- 052_path_b_graph_tables.sql
--
-- Path B (knowledge-graph substrate): the node and edge tables that turn the flat
-- signal rows into a graph. These capture the drug -> target -> disease structure
-- that Open Targets already returns and the current pipeline discards (it summarizes
-- it into free text and five scalar scores).
--
-- Edges carry their own provenance (source, and a score where one exists), so the
-- traceability invariant holds at the edge level: an edge cannot exist without its
-- two real endpoints (enforced by NOT NULL foreign keys), and it records where it
-- came from. This migration only creates structure; migration 053 (generated by
-- scripts/capture-opentargets-graph.py) backfills it.

-- ── nodes: biological targets (genes / proteins) ────────────────────────────
create table if not exists targets (
  id              uuid primary key default gen_random_uuid(),
  ensembl_gene_id text not null unique,        -- Open Targets / Ensembl id, e.g. ENSG00000091831
  hgnc_symbol     text,                         -- approved symbol, e.g. ESR1
  approved_name   text,
  created_at      timestamptz not null default now()
);

-- ── edge: drug -> target (mechanism of action) ──────────────────────────────
create table if not exists drug_targets (
  id             uuid primary key default gen_random_uuid(),
  compound_id    uuid not null references compounds(id) on delete cascade,
  target_id      uuid not null references targets(id)   on delete cascade,
  action_type    text not null default 'UNKNOWN',       -- INHIBITOR | AGONIST | ANTAGONIST | MODULATOR | ...
  mechanism_text text,
  source         text not null default 'opentargets',
  created_at     timestamptz not null default now(),
  unique (compound_id, target_id, action_type)
);

-- ── edge: target -> condition (disease association, by evidence type) ────────
create table if not exists target_conditions (
  id            uuid primary key default gen_random_uuid(),
  target_id     uuid not null references targets(id)     on delete cascade,
  condition_id  uuid not null references conditions(id)  on delete cascade,
  datatype      text not null,        -- genetic_association | known_drug | literature | animal_model | ...
  score         numeric not null,     -- per-evidence-type score (the datatypeScores OT exposes)
  overall_score numeric,              -- the target's overall association score for the condition
  source        text not null default 'opentargets',
  created_at    timestamptz not null default now(),
  unique (target_id, condition_id, datatype)
);

-- ── indexes (these are join keys for graph queries) ─────────────────────────
create index if not exists drug_targets_compound_idx     on drug_targets (compound_id);
create index if not exists drug_targets_target_idx       on drug_targets (target_id);
create index if not exists target_conditions_target_idx  on target_conditions (target_id);
create index if not exists target_conditions_cond_idx    on target_conditions (condition_id);
